### PR TITLE
[23] Add API Endpoint Documentation

### PR DESCRIPTION
**Pull request by maunga-et**
Added swagger.

### CODE REVIEW

**Comment by terrameijar** [comment]
@maunga-et  Thanks for making the updates. The flake8 linter checks were not successful, so we need to address them. Please run flake8 against the `backend` directory and fix the errors it points out.

image

**Comment by terrameijar** [comment]
@maunga-et were you able to work on this?

**Comment by maunga-et** [comment]
Yes but all the changes are in the pull request above.

**Comment by terrameijar** [comment]
@maunga-et I fixed the lint errors. I'll merge this now. Thank you for working on it.

**Pull request merged**
